# Generated by Django 4.0.1 on 2022-03-18 13:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locationgameapp', '0002_userrights'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userRights',
            new_name='userRight',
        ),
    ]
