# Generated by Django 4.0.1 on 2022-03-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationgameapp', '0003_rename_userrights_userright'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userRight',
        ),
    ]
