# Generated by Django 4.0.2 on 2022-03-20 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locationgameapp', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profilePictures'),
        ),
        migrations.CreateModel(
            name='pleaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locationgameapp.profile')),
            ],
        ),
    ]
